# Mathematical Operations in Numpy

#### astype() ---> astype() will help us out with figuring out the column in the dataset in pandas and it will be used in numpy as well for getting the data data type change of our overall array.

In [30]:
import numpy as np

In [3]:
array = np.arange(1,10).reshape(3,3)

In [4]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array.astype('float64')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [6]:
type(array)

numpy.ndarray

In [7]:
array.dtype

dtype('int64')

In [8]:
array = array.astype('float64')

In [9]:
array.dtype

dtype('float64')

In [ ]:
## Scaler Operations ---> A scaler value Operation will be done with the array or a numeric value (eg, 1,4 etc.).

In [13]:
array = np.random.random((3,3))*100
array

array([[81.26521587, 58.90725264, 15.12606551],
       [43.44255108, 54.1396779 , 42.34042603],
       [75.30875708, 17.67632379, 64.67387618]])

In [12]:
array = np.round(array)

In [15]:
array = array.astype('int32')

In [16]:
array

array([[81, 58, 15],
       [43, 54, 42],
       [75, 17, 64]], dtype=int32)

In [17]:
## Scaler operations with our Matrix or array.

In [18]:
array + 2

array([[83, 60, 17],
       [45, 56, 44],
       [77, 19, 66]], dtype=int32)

In [19]:
array*2

array([[162, 116,  30],
       [ 86, 108,  84],
       [150,  34, 128]], dtype=int32)

In [20]:
array/2

array([[40.5, 29. ,  7.5],
       [21.5, 27. , 21. ],
       [37.5,  8.5, 32. ]])

In [21]:
## We can apply scaler operations with the array in terms of arithmetic operations.

In [22]:
a =5
b=6
a>5

False

In [23]:
array

array([[81, 58, 15],
       [43, 54, 42],
       [75, 17, 64]], dtype=int32)

In [24]:
array>60

array([[ True, False, False],
       [False, False, False],
       [ True, False,  True]])

In [25]:
# Vector Operations ---> Operations will be inbetween the given number of matrices.

In [33]:
arr_1 = np.arange(1,17).reshape(4,4)

In [34]:
arr_2 = np.arange(17,33).reshape(4,4)

In [35]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
arr_2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [37]:
arr_1 + arr_2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [39]:
arr_2-arr_1

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [40]:
arr_1*arr_2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

In [41]:
arr_1/arr_2

array([[0.05882353, 0.11111111, 0.15789474, 0.2       ],
       [0.23809524, 0.27272727, 0.30434783, 0.33333333],
       [0.36      , 0.38461538, 0.40740741, 0.42857143],
       [0.44827586, 0.46666667, 0.48387097, 0.5       ]])

## Important Functions in Numpy for Machine Learning & Data Science

In [43]:
## max() ---> It is used for calculating the maximum value of the matrix or array.
## Syntax: np.max(array)

In [44]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [47]:
max_value = np.max(arr_1)
print(max_value)

16


In [49]:
array_data = np.round(np.random.random((4,4))*100).astype('int32')

In [50]:
array_data

array([[86,  3, 32, 30],
       [97, 49, 37, 91],
       [38, 92, 14, 22],
       [57,  0, 69, 83]], dtype=int32)

### axis ---> It provides us with the idea about the any operation value inside specific row or column or we can get a specific value row wise and column wise.

#### axis = 0 ---> It is used for column wise operations.
#### axis = 1 ---> It is used for row wise operations.

In [52]:
np.max(array_data,axis=0)

array([97, 92, 69, 91], dtype=int32)

In [54]:
np.max(array_data,axis=1)

array([86, 97, 92, 83], dtype=int32)

In [55]:
## min() ---> It is used for calculating the minimum value of the matrix or array.
## Syntax: np.min(array)

In [56]:
array_data

array([[86,  3, 32, 30],
       [97, 49, 37, 91],
       [38, 92, 14, 22],
       [57,  0, 69, 83]], dtype=int32)

In [57]:
np.min(array_data)

np.int32(0)

In [58]:
np.min(array_data,axis=0)

array([38,  0, 14, 22], dtype=int32)

In [59]:
np.min(array_data,axis=1)

array([ 3, 37, 14,  0], dtype=int32)

In [ ]:
## sum() ---> It is used for calculating the sum of the matrix or array.
## Syntax: np.sum(array)

In [61]:
array_data

array([[86,  3, 32, 30],
       [97, 49, 37, 91],
       [38, 92, 14, 22],
       [57,  0, 69, 83]], dtype=int32)

In [62]:
np.sum(array_data)

np.int64(800)

In [63]:
np.sum(array_data,axis=0)

array([278, 144, 152, 226])

In [64]:
np.sum(array_data,axis=1)

array([151, 274, 166, 209])

In [69]:
## Prod() ---> It is used for calculating the product of alol values of matrix or array.
## Syntax: np.prod(array)

In [71]:
array = np.arange(1,10)

In [72]:
np.prod(array)

np.int64(362880)

In [73]:
np.prod(array_data)

np.int64(0)

In [ ]:
np.prod(array_data,axis=0) #column wise

array([18068772,        0,  1143744,  4984980])

In [ ]:
np.prod(array_data,axis=1) #Row wise

array([  247680, 16003351,  1076768,        0])