# Mathematical Operations in Numpy

#### astype() ---> astype() will help us out with figuring out the column in the dataset in pandas and it will be used in numpy as well for getting the data data type change of our overall array.

In [2]:
import numpy as np

In [3]:
array = np.arange(1,10).reshape(3,3)

In [4]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array.astype('float64')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [6]:
type(array)

numpy.ndarray

In [7]:
array.dtype

dtype('int64')

In [8]:
array = array.astype('float64')

In [9]:
array.dtype

dtype('float64')

In [ ]:
## Scaler Operations ---> A scaler value Operation will be done with the array or a numeric value (eg, 1,4 etc.).

In [13]:
array = np.random.random((3,3))*100
array

array([[81.26521587, 58.90725264, 15.12606551],
       [43.44255108, 54.1396779 , 42.34042603],
       [75.30875708, 17.67632379, 64.67387618]])

In [12]:
array = np.round(array)

In [15]:
array = array.astype('int32')

In [16]:
array

array([[81, 58, 15],
       [43, 54, 42],
       [75, 17, 64]], dtype=int32)

In [17]:
## Scaler operations with our Matrix or array.

In [18]:
array + 2

array([[83, 60, 17],
       [45, 56, 44],
       [77, 19, 66]], dtype=int32)

In [19]:
array*2

array([[162, 116,  30],
       [ 86, 108,  84],
       [150,  34, 128]], dtype=int32)

In [20]:
array/2

array([[40.5, 29. ,  7.5],
       [21.5, 27. , 21. ],
       [37.5,  8.5, 32. ]])

In [21]:
## We can apply scaler operations with the array in terms of arithmetic operations.

In [22]:
a =5
b=6
a>5

False