# Numpy Important Formulas

In [1]:
import numpy as np

In [2]:
numpy_array = np.array([1,2,3,4,5])

In [3]:
numpy_array

array([1, 2, 3, 4, 5])

In [4]:
type(numpy_array)

numpy.ndarray

In [ ]:
TwoDArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
TwoDArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
ThreeDArray = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

In [12]:
ThreeDArray

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [13]:
type(ThreeDArray)

numpy.ndarray

In [14]:
## np.array() ---> Used for creating the multidimentional array.

In [15]:
## dtype parameter ---> Used for desiding the size of the data we are going to store inside the array.

In [16]:
np.array([1,2,3,4,5], dtype=np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [17]:
np.array([7,8,9,10,11], dtype=np.int64)

array([ 7,  8,  9, 10, 11])

In [19]:
np.array([1,0,3,4,5], dtype=bool)

array([ True, False,  True,  True,  True])

In [20]:
# range() for i in range(15)
empty_list = []
for i in range(16):
    empty_list.append(i)
print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [24]:
array_Range = np.arange(16)
print(array_Range)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [25]:
type(array_Range)

numpy.ndarray

## arange ---> It helps us out with providing the values over a certain range.

In [27]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])