# Numpy Important Formulas

In [2]:
import numpy as np

In [2]:
numpy_array = np.array([1,2,3,4,5])

In [3]:
numpy_array

array([1, 2, 3, 4, 5])

In [4]:
type(numpy_array)

numpy.ndarray

In [ ]:
TwoDArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
TwoDArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
ThreeDArray = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

In [12]:
ThreeDArray

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [13]:
type(ThreeDArray)

numpy.ndarray

In [14]:
## np.array() ---> Used for creating the multidimentional array.

In [15]:
## dtype parameter ---> Used for desiding the size of the data we are going to store inside the array.

In [16]:
np.array([1,2,3,4,5], dtype=np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [17]:
np.array([7,8,9,10,11], dtype=np.int64)

array([ 7,  8,  9, 10, 11])

In [19]:
np.array([1,0,3,4,5], dtype=bool)

array([ True, False,  True,  True,  True])

In [20]:
# range() for i in range(15)
empty_list = []
for i in range(16):
    empty_list.append(i)
print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [24]:
array_Range = np.arange(16)
print(array_Range)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [25]:
type(array_Range)

numpy.ndarray

## arange ---> It helps us out with providing the values over a certain range.

In [27]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [6]:
arrange_data= np.arange(1,10)

In [7]:
arrange_data.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### reshape() : It helps us out with changing the shape of of an array as per our need.

In [8]:
np.arange(2,17,2).reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

### ones() ---> Used for creating the array of ones.

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### zeros() ---> Used for creating the array of zeros

In [12]:
np.zeros((3,5), dtype=np.int32)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

#### random() ---> It helps us out with generating any random values from 0 to 1 inside our matrix.

In [13]:
np.random.random((3,4))

array([[0.74893047, 0.42296698, 0.01910665, 0.48239551],
       [0.0553189 , 0.93244389, 0.37047379, 0.38561124],
       [0.51120423, 0.09075971, 0.27860995, 0.40336677]])

#### Identity() ---> It helps us out with creating the matrix as an Identity matrix. Rows and colums should be same.

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Linspace() ---> It makes sure that every value within the given range is going to have similar distance from each other.

In [21]:
np.linspace(-10,10,10, dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

# Attributes

#### ndim ---> ndim stands for n-dimention.

In [22]:
arr = np.array([1,2,3])

In [23]:
arr

array([1, 2, 3])

In [24]:
arr.ndim

1

In [27]:
array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [28]:
array.ndim

3

In [29]:
np.array([[1,2,3],[4,5,6]]).ndim

2

In [30]:
print(array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### shape ---> It provides us with the idea about rows and column in our dataset or in our array.

In [32]:
Array = np.array([[1,2,3],[4,5,6],[7,8,9]])
Array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
Array.shape

(3, 3)

In [34]:
Array3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
Array3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
Array3D.shape

(2, 2, 3)

#### size ---> Total number of elements present in our data set.

In [36]:
array_elements = np.arange(5,57)

In [37]:
array_elements.size

52

In [39]:
np.array([[1,2,3],[4,5,6]]).itemsize

8

In [41]:
np.array([[1,2,3],[4,5,6]], dtype=np.int32).itemsize

4

#### Itemsize ---> Provides with the idea about the size of a unique element inside our array in byte.

#### dtype ---> It provides us with the idea about the type of every item inside our array.

In [42]:
np.array([[1,2,3],[4,5,6]]).dtype

dtype('int64')