# Statistical Functions in Numpy

In [1]:
## mean() ---> It will provide mean value of the array.


In [3]:
import numpy as np

In [19]:
array = np.round(np.random.random((4,4))*100).astype(int)

In [6]:
array

array([[65, 35, 40,  5],
       [23, 38, 37, 24],
       [59, 34, 49, 59],
       [74, 69, 33, 13]])

In [7]:
np.mean(array)

np.float64(41.0625)

In [8]:
np.mean(array, axis=0) ## It will provide mean value of the column.

array([55.25, 44.  , 39.75, 25.25])

In [9]:
np.mean(array, axis=1) ## It will provide mean value of the row.

array([36.25, 30.5 , 50.25, 47.25])

In [10]:
## std() ---> It will provide standard deviation of the array.

In [11]:
np.std(array)

np.float64(19.411558251464513)

In [12]:
np.std(array, axis=0)

array([19.36975736, 14.50861813,  5.88960949, 20.62007517])

In [13]:
np.std(array, axis=1)

array([21.32340264,  7.01783442, 10.23169096, 25.32168043])

In [14]:
## median() ---> It will provide median value of the array.

In [15]:
np.median(array)

np.float64(37.5)

In [16]:
# axis=0 ---> It will provide  value of the column.
# axis=1 ---> It will provide value of the row.

In [17]:
## var ---> Variance of all values in the matrix or array.
## syntax: np.var(array, axis=0)

In [20]:
array

array([[10, 67,  3, 83],
       [13, 46, 69, 27],
       [41, 43, 29, 12],
       [34, 42, 93, 24]])

In [21]:
np.var(array)

np.float64(665.0625)

## Trigonomatric Functions

In [22]:
#sin() ---> It will provide sin value of the array.

In [23]:
np.sin(0)

np.float64(0.0)

In [24]:
np.sin(90)

np.float64(0.8939966636005579)

In [25]:
np.tan(90)

np.float64(-1.995200412208242)

In [26]:
np.cos(1)

np.float64(0.5403023058681398)

In [27]:
# Dot product of two array/Matrices.
# Syntax: np.dot(matrix1, matrix2)
# rule: matrix1.shape[1] == matrix2.shape[0]

In [4]:
matrix_1 = np.round(np.random.random((3,4))*100).astype(int)
matrix_2 = np.round(np.random.random((4,2))*100).astype(int)

In [5]:
matrix_1

array([[14, 51,  9, 13],
       [41, 69, 47, 16],
       [46, 14, 83, 39]])

In [40]:
matrix_2

array([[63, 55],
       [54, 68],
       [27, 37],
       [53, 32]])

In [41]:
np.dot(matrix_1, matrix_2)

array([[9325, 9338],
       [7991, 7100],
       [7213, 7370]])

In [42]:
np.dot(matrix_2, matrix_1)

ValueError: shapes (4,2) and (3,4) not aligned: 2 (dim 1) != 3 (dim 0)

In [44]:
# log() ---> To calculate the log of all values in matrix.
# Syntax: np.log()

In [8]:
matrix_1

array([[14, 51,  9, 13],
       [41, 69, 47, 16],
       [46, 14, 83, 39]])

In [9]:
np.log(matrix_1)

array([[2.63905733, 3.93182563, 2.19722458, 2.56494936],
       [3.71357207, 4.2341065 , 3.8501476 , 2.77258872],
       [3.8286414 , 2.63905733, 4.41884061, 3.66356165]])

In [11]:
## exp() ---> It will provide exponent of all values in matrix.
# Syntax: np.exp(matrix)

In [12]:
np.exp(matrix_1)

array([[1.20260428e+06, 1.40934908e+22, 8.10308393e+03, 4.42413392e+05],
       [6.39843494e+17, 9.25378173e+29, 2.58131289e+20, 8.88611052e+06],
       [9.49611942e+19, 1.20260428e+06, 1.11286375e+36, 8.65934004e+16]])

In [13]:
## round() ---> It will round off the values in matrix.
# Syntax: np.round(matrix, decimals=0)
# Round off value for 1.7---> 2
## Round off value for 1.4---> 1

In [20]:
array = np.random.random((3,4))*100
array

array([[60.97757437, 89.03246935, 29.33115874, 76.9315686 ],
       [21.81605377,  3.53048167,  9.75313033, 50.47024349],
       [ 8.97287998, 17.36689711, 43.71269241, 86.29125772]])

In [21]:
np.round(array, decimals=0)

array([[61., 89., 29., 77.],
       [22.,  4., 10., 50.],
       [ 9., 17., 44., 86.]])

#### round() ---> 1.6 ---> 2 1.3 --->1
#### floor() ---> 1.6 ---> 1 1.3 ---> 1
#### ceil() ---> 1.6 ---> 2 1.3 ---> 2

In [23]:
## ceil ---> next corresponding value.
## syntax: np.ceil(matrix)

In [24]:
array

array([[60.97757437, 89.03246935, 29.33115874, 76.9315686 ],
       [21.81605377,  3.53048167,  9.75313033, 50.47024349],
       [ 8.97287998, 17.36689711, 43.71269241, 86.29125772]])

In [26]:
np.ceil(array)

array([[61., 90., 30., 77.],
       [22.,  4., 10., 51.],
       [ 9., 18., 44., 87.]])

In [27]:
## floor ---> previous corresponding value.
## syntax: np.floor(matrix)

In [28]:
np.floor(array)

array([[60., 89., 29., 76.],
       [21.,  3.,  9., 50.],
       [ 8., 17., 43., 86.]])

In [29]:
## transpose() ---> It calculates the transpose of the matrix.
## syntax: np.transpose(matrix)
## transpose of matrix is obtained by changing the rows into columns and columns into rows.

In [30]:
array

array([[60.97757437, 89.03246935, 29.33115874, 76.9315686 ],
       [21.81605377,  3.53048167,  9.75313033, 50.47024349],
       [ 8.97287998, 17.36689711, 43.71269241, 86.29125772]])

In [31]:
np.transpose(array)

array([[60.97757437, 21.81605377,  8.97287998],
       [89.03246935,  3.53048167, 17.36689711],
       [29.33115874,  9.75313033, 43.71269241],
       [76.9315686 , 50.47024349, 86.29125772]])

In [32]:
## Ravel ---> It will convert the matrix into 1D array.
## syntax: np.ravel(matrix)

In [34]:
Array3D = np.round(np.random.random((3,4,2))*100).astype(int)

In [35]:
Array3D

array([[[ 4, 31],
        [68, 53],
        [45, 28],
        [47, 99]],

       [[15, 97],
        [79, 92],
        [ 0, 52],
        [ 5, 59]],

       [[97, 22],
        [19, 66],
        [27,  9],
        [ 3, 11]]])

In [36]:
np.ravel(Array3D)

array([ 4, 31, 68, 53, 45, 28, 47, 99, 15, 97, 79, 92,  0, 52,  5, 59, 97,
       22, 19, 66, 27,  9,  3, 11])

## Indexing and slicing in numpy.

In [37]:
## indexing --->list[,size-1] ---> To have the access over the values.

In [38]:
array = np.round(np.random.random((3,4))*100).astype(int)

In [39]:
array

array([[65, 62, 75, 72],
       [68, 33, 64,  6],
       [78, 15, 18, 25]])

In [40]:
array_1 = np.arange(1,10)

In [41]:
array_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
array_1[6]

np.int64(7)

In [46]:
array[2,3]

np.int64(25)

In [47]:
## Indexing in 2D array ---> list[row_index, column_index]

In [48]:
## Indexing in 3D array ---> list[depth_index, row_index, column_index]

In [49]:
array3D = np.round(np.random.random((3,4,2))*100).astype(int)

In [50]:
array3D

array([[[38, 91],
        [11, 77],
        [70, 82],
        [90,  7]],

       [[37, 81],
        [54,  2],
        [65, 15],
        [16, 40]],

       [[ 9, 81],
        [ 4, 72],
        [19, 99],
        [27, 89]]])

In [52]:
array3D[1,1,1]

np.int64(2)

In [53]:
array

array([[65, 62, 75, 72],
       [68, 33, 64,  6],
       [78, 15, 18, 25]])

In [55]:
## slicing ---> list[start_index:end_index:step]
## 2d array ---> list[row_start_index:row_end_index:row_step, column_start_index:column_end_index:column_step]

In [ ]:
array[:,2] # column 3

array([75, 64, 18])

In [ ]:
array[0,:] # row 1

array([65, 62, 75, 72])

In [62]:
array[1:3,2:4]

array([[64,  6],
       [18, 25]])